spring.application.name=oudiac


spring.datasource.url=jdbc:postgresql://localhost:5432/oudiac
spring.datasource.username=postgres
spring.datasource.password=Abcd@1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql= true
spring.jpa.hibernate.ddl-auto=update

#server.port=8081

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=iloveyoumyjan17@gmail.com
spring.mail.password=kkgqonvujlcypotu

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

FRONT_END_URL=http://localhost:5173


supabase.s3.endpoint=https://izzphtokddbewzuzolhr.storage.supabase.co/storage/v1/s3
supabase.s3.access-key=0b9fc52d50daaaa4767385b1da3e935b
supabase.s3.secret-key=f1c99dbcd859b4573b18c179ce7a837739cc209992168349dd86416766463f90
supabase.s3.bucket=images

S3_STORAGE_BASE_URL=https://izzphtokddbewzuzolhr.supabase.co/storage/v1/object/public/images/